task_manager/labels/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.labels_list, name='labels-list'),
    path('create/', views.label_create, name='label_create'),
    path('<int:pk>/update/', views.label_update, name='label_update'),
    path('<int:pk>/delete/', views.label_delete, name='label_delete'),
]

task_manager/statuses/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_statuses, name='list_statuses'),
    path('create/', views.create_status, name='create_status'),
    path('<int:pk>/update/', views.update_status, name='update_status'),
    path('<int:pk>/delete/', views.delete_status, name='delete_status'),
]

task_manager/tasks/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.task_list, name='task_list'),
    path('create/', views.task_create, name='task_create'),
    path('<int:pk>/update/', views.task_update, name='task_update'),
    path('<int:pk>/delete/', views.task_delete, name='task_delete'),
    path('<int:pk>/', views.task_detail, name='task_detail'),

]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (IndexView, register, user_list,
                    login_view, logout_view,
                    user_update_view, user_delete_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='root'),
    path('users/create/', register, name='register'),
    path('users/', user_list, name='user-list'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('users/<int:pk>/update/', user_update_view, name='user_update'),
    path('users/<int:pk>/delete/', user_delete_view, name='user_delete'),
    path('users/<int:pk>/delete/', user_delete_view, name='user_delete'),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
]

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    username = models.CharField(max_length=150, unique=True)
    password = models.CharField(max_length=100)
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.username

task_manager/tasks/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.models import CustomUser


class Task(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    description = models.TextField(verbose_name=_('Description'))
    status = models.ForeignKey(Status,
                               on_delete=models.CASCADE,
                               related_name='tasks',
                               default=1,
                               verbose_name=_('Status'))
    author = models.ForeignKey(CustomUser,
                               related_name='author_tasks',
                               on_delete=models.CASCADE,
                               verbose_name=_('Author'))
    executor = models.ForeignKey(CustomUser,
                                 related_name='executor_tasks',
                                 on_delete=models.CASCADE,
                                 null=True,
                                 verbose_name=_('Executor'))
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name=_('Дата создания'))
    label = models.ManyToManyField(Label, related_name='label')

    def __str__(self):
        return self.name

task_manager/labels/forms.py
from django import forms
from .models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ['name']
        labels = {
            'name': 'Имя',
        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Имя'}),
        }

task_manager/statuses/forms.py
from django import forms
from .models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name']
        labels = {
            'name': 'Имя',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',
                                                    'placeholder': 'Имя'})
        }

    def __init__(self, *args, **kwargs):
        super(StatusForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.name:
            self.fields['name'].widget.attrs['placeholder']\
                = self.instance.name

task_manager/labels/views.py
from task_manager.labels.forms import LabelForm
from django.shortcuts import render, redirect, get_object_or_404
from task_manager.labels.models import Label
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def label_create(request):
    if request.method == 'POST':
        form = LabelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Метка успешно создана.')
            return redirect('labels-list')
    else:
        form = LabelForm()
    return render(request,
                  'labels/label_create.html', {'form': form})


def label_delete(request, pk):
    label = get_object_or_404(Label, pk=pk)
    if request.method == 'POST':
        if label.label.exists():
            messages.error(request,
                           'Невозможно удалить метку,'
                           ' потому что она используется')
            return redirect('labels-list')
        else:
            label.delete()
            messages.success(request, 'Метка успешно удалена.')
            return redirect('labels-list')
    else:
        return render(request, 'labels/label_delete.html',
                      {'label': label})


def label_update(request, pk):
    label = get_object_or_404(Label, pk=pk)
    if request.method == 'POST':
        form = LabelForm(request.POST, instance=label)
        if form.is_valid():
            form.save()
            messages.success(request, 'Метка успешно изменена')
            return redirect('labels-list')
        else:
            messages.error(request, 'Ошибка при обновлении метки.')
    else:
        form = LabelForm(instance=label)
    return render(request,
                  'labels/label_update.html',
                  {'form': form, 'label': label})


def labels_list(request):
    labels = Label.objects.all()
    return render(request, 'labels/labels.html',
                  {'labels': labels})

task_manager/statuses/views.py
from task_manager.statuses.forms import StatusForm
from django.shortcuts import render, redirect, get_object_or_404
from task_manager.statuses.models import Status
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required(login_url='/require_login/')
def list_statuses(request):
    statuses = Status.objects.all()
    return render(request, 'statuses/statuses.html', {'statuses': statuses})


def require_login(request):
    messages.error(request,
                   'Вы не авторизованы! Пожалуйста, выполните вход.')
    return redirect('login')


@login_required
def create_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Статус успешно создан')
            return redirect('list_statuses')
    else:
        form = StatusForm()
    return render(request, 'statuses/create_status.html', {'form': form})


@login_required
def update_status(request, pk):
    status = get_object_or_404(Status, pk=pk)
    if request.method == 'POST':
        form = StatusForm(request.POST, instance=status)
        if form.is_valid():
            form.save()
            messages.success(request, 'Статус успешно изменен')
            return redirect('list_statuses')
    else:
        form = StatusForm(instance=status)
    return render(request,
                  'statuses/update_status.html',
                  {'form': form, 'status': status})


@login_required
def delete_status(request, pk):
    status = get_object_or_404(Status, pk=pk)
    if request.method == 'POST':
        if status.tasks.exists():
            messages.error(request,
                           'Невозможно удалить статус,'
                           ' потому что он используется')
            return redirect('list_statuses')
        else:
            status.delete()
            messages.success(request, 'Статус успешно удален')
            return redirect('list_statuses')
    else:
        # Перенаправление на страницу подтверждения удаления
        return render(request,
                      'statuses/delete_status.html',
                      {'status': status})

task_manager/tasks/views.py
from task_manager.tasks.forms import TaskForm
from django.shortcuts import render, redirect, get_object_or_404
from task_manager.models import CustomUser
from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.tasks.models import Task
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import logging

logger = logging.getLogger(__name__)


def task_list(request):
    tasks = Task.objects.select_related(''
                                        'status',
                                        'executor'
                                        ).prefetch_related(
        'label').all()
    statuses = Status.objects.all()
    executors = CustomUser.objects.filter(
        executor_tasks__isnull=False).distinct()
    labels = Label.objects.all()

    status_id = request.GET.get('status')
    if status_id:
        tasks = tasks.filter(status_id=status_id)

    executor_id = request.GET.get('executor')
    if executor_id:
        tasks = tasks.filter(executor_id=executor_id)

    label_id = request.GET.get('label')
    if label_id:
        tasks = tasks.filter(label__id=label_id)

    if 'own_tasks' in request.GET:
        tasks = tasks.filter(author=request.user)

    logger.debug('Filtered tasks: %s', list(tasks.values('id', 'name')))
    logger.debug('Filtered status ID: %s', status_id)
    logger.debug('Filtered executor ID: %s', executor_id)
    logger.debug('Filtered label ID: %s', label_id)

    return render(request, 'tasks/tasks.html', {
        'tasks': tasks,
        'statuses': statuses,
        'executors': executors,
        'labels': labels,
    })


@login_required
def task_create(request):
    form = TaskForm(request.POST or None)
    labels = Label.objects.all()
    if request.method == 'POST':
        logger.info('Received POST request with data: %s',
                    request.POST)
        if form.is_valid():
            logger.info('Form is valid')
            task = form.save(commit=False)
            task.author = request.user
            task.save()
            task.label.set(request.POST.getlist('label'))
            messages.success(request, 'Задача успешно создана')
            return redirect('task_list')
        else:
            logger.warning('Form is not valid: %s', form.errors)
    statuses = Status.objects.all()
    users = CustomUser.objects.all()
    return render(request, 'tasks/task_form.html', {
        'form': form,
        'statuses': statuses,
        'users': users,
        'labels': labels
    })


@login_required
def task_update(request, pk):
    task = get_object_or_404(Task, pk=pk)
    statuses = Status.objects.all()
    users = CustomUser.objects.all()
    labels = Label.objects.all()

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            messages.success(request, 'Задача успешно изменена')
            return redirect('task_list')
    else:
        form = TaskForm(instance=task)

    return render(request, 'tasks/task_update.html', {
        'form': form,
        'statuses': statuses,
        'users': users,
        'labels': labels,
        'task': task
    })


@login_required
def task_detail(request, pk):
    task = Task.objects.get(pk=pk)
    return render(request, 'tasks/task_detail.html', {'task': task})


@login_required
def task_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)

    if request.user != task.author:
        messages.error(request,
                       'Задачу может удалить только ее автор')
        return redirect('task_list')

    if request.method == 'POST':
        task.delete()
        messages.success(request,
                         'Задача успешно удалена')
        return redirect('task_list')

    return render(request, 'tasks/task_delete.html', {'task': task})

task_manager/views.py
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from task_manager.forms import (CustomUserCreationForm,
                                LoginForm)
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from task_manager.models import CustomUser
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import logging
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy

logger = logging.getLogger(__name__)


def index(request):
    return HttpResponse("Hello, world. You're at the pollapp index.")


class IndexView(TemplateView):
    template_name = "index.html"
    extra_context = {'header': _('Task manager')}


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            messages.success(request, 'Пользователь успешно зарегистрирован')
            user.is_active = True
            user.save()
            return redirect('login')  # Перенаправление на страницу входа
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/register.html', {'form': form})


def user_list(request):
    users = CustomUser.objects.all()
    return render(request, 'users/users.html', {'users': users})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Вы залогинены')
                return redirect('root')
            else:
                messages.error(request, 'Неверное имя пользователя или пароль')
                return render(request, 'users/login.html', {'form': form})
        else:
            for field in form.errors:
                form[field].field.widget.attrs['class'] += ' is-invalid'
            return render(request, 'users/login.html', {'form': form})
    else:
        form = LoginForm()
        return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    logout(request)
    messages.success(request, gettext_lazy('Вы разлогинены'))
    next_page = reverse_lazy('root')
    return redirect(next_page)


@login_required
def user_update_view(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)
    form = CustomUserCreationForm(instance=user)

    if user != request.user:
        messages.error(request,
                       'У вас нет прав для изменения другого пользователя.')
        return redirect('user-list')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Пользователь успешно изменен')
            return redirect('user-list')

    return render(request, 'users/user_update.html', {'form': form})


@login_required
def user_delete_view(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)

    if user != request.user:
        messages.error(request,
                       'У вас нет прав для изменения другого пользователя.')
        return redirect('user-list')

    if request.method == 'GET':
        return render(request, 'users/user_delete.html', {'user': user})

    if request.method == 'POST':
        if user.author_tasks.exists() or user.executor_tasks.exists():
            messages.error(request,
                           'Невозможно удалить пользователя,'
                           ' потому что он используется')
            return redirect('user-list')
        else:
            user.delete()
            logout(request)
            messages.success(request, 'Пользователь успешно удален.')
            return HttpResponseRedirect(reverse('user-list'))

    return redirect('user-list')

task_manager/templates/tasks/task_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Удалить задачу' %}{% endblock %}

{% block content %}
  <h2>{% trans 'Удалить задачу' %}</h2>

  <p>{% trans 'Вы уверены, что хотите удалить эту задачу?' %}</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">{% trans 'Yes, delete' %}</button>
  </form>

{% endblock %}

task_manager/templates/tasks/task_detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_messages %}
{% load i18n %}

{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4">{% trans "Task view" %}</h1>

    <div class="card">
        <div class="card-header bg-secondary text-white">
            <h2>{{ task.name }}</h2>
        </div>
        <div class="card-body bg-light">
            <p>{{ task.description }}</p>
            <hr>
            <div class="container">
                <div class="row p-1">
                    <div class="col">{% trans "Author" %}</div>
                    <div class="col">{{ task.author.first_name }} {{ task.author.last_name }}</div>
                </div>
                <div class="row p-1">
                    <div class="col">{% trans "Executor" %}</div>
                    <div class="col">{{ task.executor.first_name }} {{ task.executor.last_name }}</div>
                </div>
                <div class="row p-1">
                    <div class="col">{% trans "Status" %}</div>
                    <div class="col">{{ task.status }}</div>
                </div>
                <div class="row p-1">
                    <div class="col">{% trans "Created at" %}</div>
                    <div class="col">{{ task.created_at }}</div>
                </div>
                <div class="row p-1">
                    <div class="col">
                        <h6>{% trans "Labels:" %}</h6>
                        {% for label in task.label.all %}
                        <ul>
                            <li>{{ label.name }}</li>
                        </ul>
                        {% endfor %}
                    </div>
                </div>
                <div class="row p-1">
                    <div class="col">
                        <a href="{% url 'task_update' task.id %}">{% trans "Edit" %}</a>
                        <br>
                        <a href="{% url 'task_delete' task.id %}">{% trans "Delete" %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task_manager/templates/tasks/task_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}


<div class="task-create-container">
  <h2>{% trans 'Task Create' %}</h2>
  <form method="post" class="task-create-form">
    {% csrf_token %}

    <!-- Поле для name -->
       <div class="form-group">
      {% trans 'Name' as name_label %}
      <label for="id_name">{{ name_label|cut:":" }}</label>
      <input type="text"
             id="id_name"
             name="name"
             class="form-control"
             placeholder="{% trans 'Name' %}"
             required
             aria-required="true"
             oninvalid="this.setCustomValidity('{% trans 'Please fill out this field' %}')"
             oninput="setCustomValidity('')">
    </div>

    <!-- Поле для description -->

   <div class="form-group">
  {% trans 'Overview' as description_label %}
  <label for="id_description">{{ description_label|cut:":" }}</label>
  <textarea id="id_description"
            name="description"
            class="form-control"
            placeholder="{% trans 'Overview' %}"
            rows="10"
            oninvalid="this.setCustomValidity('{% trans 'Please fill out this field' %}')"
            oninput="setCustomValidity('')">{{ form.description.value|default:'' }}</textarea>
  {{ form.description.errors }}
</div>

    <!-- Поле для status -->
   <div class="mb-3"><label class="form-label" for="id_status">{% trans "Status" %}</label>
       <select name="status" class="form-select" required="" id="id_status">
        <option value="" selected disabled>---------</option>
        {% for status in statuses %}
          <option value="{{ status.id }}">{{ status.name }}</option>
        {% endfor %}
      </select>
    </div>

<!-- Поле для executor -->
<div class="form-group">
  <label class="form-label" for="id_executor">{% trans "Executor" %}</label>
  <select name="executor" id="id_executor" class="form-select">
    <option value="" selected disabled>---------</option>
    {% for user in users %}
      <option value="{{ user.id }}">{{ user.first_name }} {{ user.last_name }}</option>
    {% endfor %}
  </select>
</div>

    <!-- Поле для labels -->
    <!-- Поле для labels -->
      <label for="label">{% trans 'Labels' %}</label>
<select multiple id="label" name="label" class="form-control form-control-sm">
  {% for label in labels %}
    <option value="{{ label.id }}">{{ label.name }}</option>
  {% endfor %}
</select>

    <button type="submit" class="btn btn-primary mt-3">{% trans 'Create' %}</button>
  </form>
</div>

{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/task-create.css' %}">
{% endblock %}

task_manager/templates/tasks/task_update.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}


<div class="task-form-container">
  <h2>{% trans 'Task Modification' %}</h2>
  <form method="post" class="task-form">
    {% csrf_token %}

    <div class="form-group">
      <label for="id_name">{% trans "Name" %}</label>
      <input type="text"
             id="id_name"
             name="name"
             value="{{ form.name.value|default_if_none:'' }}"
             class="form-control"
             placeholder="{% trans 'Name' %}"
             required
             aria-required="true"
             oninvalid="this.setCustomValidity('{% trans 'Please fill out this field' %}')"
             oninput="setCustomValidity('')">
      {{ form.name.errors }}
    </div>

<!-- Поле для description -->
<div class="form-group">
  {% trans 'Overview' as description_label %}
  <label for="id_description">{{ description_label|cut:":" }}</label>
  <textarea id="id_description"
            name="description"
            class="form-control"
            placeholder="{% trans 'Description' %}"
            rows="10"
            oninvalid="this.setCustomValidity('{% trans 'Please fill out this field' %}')"
            oninput="setCustomValidity('')">{{ form.description.value|default:'' }}</textarea>
  {{ form.description.errors }}
</div>
    <!-- Поле для status -->
    <div class="form-group">
      {% trans 'Status' as status_label %}
      <label for="id_status">{{ status_label|cut:":" }}</label>
      <select name="status" id="id_status" class="form-select" required>
        <option value="" disabled>{{ form.status.empty_label }}</option>
        {% for status in statuses %}
          <option value="{{ status.id }}" {% if status.id == form.status.value %}selected{% endif %}>{{ status.name }}</option>
        {% endfor %}
      </select>
      {{ form.status.errors }}
    </div>

    <!-- Поле для executor -->
    <div class="form-group">
      <label for="id_executor">{% trans "Executor" %}</label>
      <select name="executor" id="id_executor" class="form-select">
        <option value="" selected disabled>{% trans "---------" %}</option>
        {% for user in users %}
          <option value="{{ user.id }}" {% if user.id == form.executor.value %}selected{% endif %}>{{ user.first_name }} {{ user.last_name }}</option>
        {% endfor %}
      </select>
      {{ form.executor.errors }}
    </div>


    <!-- Поле для labels -->
    <div class="form-group">
      {% trans 'Labels' as labels_label %}
      <label for="id_labels">{{ labels_label|cut:":" }}</label>
      <select name="label" id="id_labels" class="form-select" multiple>
        {% for label in labels %}
          <option value="{{ label.id }}" {% if label.id in form.label.value %}selected{% endif %}>{{ label.name }}</option>
        {% endfor %}
      </select>
      {{ form.label.errors }}
    </div>

    <button type="submit" class="btn btn-primary mt-3">{% trans 'Edit' %}</button>
  </form>
</div>

{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/task-form.css' %}">
{% endblock %}

task_manager/templates/tasks/tasks.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  <h2>{% trans 'Tasks' %}</h2>
  <a href="{% url 'task_create' %}" class="btn btn-success mb-3">{% trans 'Create task' %}</a>

  <form method="get" class="form-inline">
    <!-- Фильтр Статус -->
    <div class="form-group mb-2">
      <label class="form-label" for="id_status">{% trans 'Status' %}</label>
      <select name="status" class="form-select ml-2 mr-3 {% if request.GET.status or request.GET.status == "" %}is-valid{% endif %}" id="id_status">
        <option value="" {% if request.GET.status == "" or not request.GET.status %}selected{% endif %}>---------</option>
        {% for status_obj in statuses %}
          <option value="{{ status_obj.id }}" {% if request.GET.status == status_obj.id|stringformat:"s" %}selected{% endif %}>
            {{ status_obj.name }}
          </option>
        {% empty %}
          <option value="" disabled>{% trans 'No available statuses' %}</option>
        {% endfor %}
      </select>
    </div>

    <!-- Фильтр Исполнитель -->
    <div class="form-group mb-2">
      <label class="form-label" for="id_executor">{% trans 'Executor' %}</label>
      <select name="executor" class="form-select mr-3 ml-2 {% if request.GET.executor or request.GET.executor == "" %}is-valid{% endif %}" id="id_executor">
        <option value="" {% if request.GET.executor == "" or not request.GET.executor %}selected{% endif %}>---------</option>
        {% for executor_obj in executors %}
          <option value="{{ executor_obj.id }}" {% if request.GET.executor == executor_obj.id|stringformat:"s" %}selected{% endif %}>
            {{ executor_obj.get_full_name }}
          </option>
        {% empty %}
        {% endfor %}
      </select>
    </div>

    <!-- Фильтр Метка -->
    <!-- Фильтр Метка -->
    <div class="form-group mb-2">
      <label class="form-label" for="id_label">{% trans 'Label' %}</label>
      <select name="label" class="form-select mr-3 ml-2 {% if request.GET.label or request.GET.label == "" %}is-valid{% endif %}" id="id_label">
        <option value="" {% if request.GET.label == "" or not request.GET.label %}selected{% endif %}>---------</option>
        {% for label in labels %}
          <option value="{{ label.id }}" {% if request.GET.label == label.id|stringformat:"s" %}selected{% endif %}>
            {{ label.name }}
          </option>
        {% empty %}
          <option value="" disabled>{% trans 'No available labels' %}</option>
        {% endfor %}
      </select>
    </div>

<!-- Фильтр Только свои задачи -->
<div class="form-group mb-2">
  <input type="checkbox" name="own_tasks" id="own_tasks" {% if request.GET.own_tasks %}checked{% endif %}>
  <label for="own_tasks" class="form-label {% if request.GET.own_tasks != None %}is-valid{% endif %}">{% trans 'Only my tasks' %}</label>
</div>

    <!-- Кнопка Показать -->
<!-- Кнопка отправки формы фильтрации -->
<div class="form-group mb-2">
  <button type="submit" class="btn btn-primary">{% trans 'Show' %}</button>
</div>

  <table class="table table-striped mt-4">
    <thead>
      <tr>
        <th scope="col">{% trans 'ID' %}</th>
        <th scope="col">{% trans 'Name' %}</th>
        <th scope="col">{% trans 'Status' %}</th>
        <th scope="col">{% trans 'Author' %}</th>
        <th scope="col">{% trans 'Executor' %}</th>
        <th scope="col">{% trans 'Creation date' %}</th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
        <tr>
          <th scope="row">{{ task.id }}</th>
          <td><a href="{% url 'task_detail' task.id %}">{{ task.name }}</a></td>
          <td>{{ task.status.name }}</td>
          <td>{{ task.author.get_full_name }}</td>
          <td>{{ task.executor.first_name }} {{ task.executor.last_name }}</td>
          <td>{{ task.created_at }}</td>
          <td>
            <div><a href="{% url 'task_update' task.id %}">{% trans "Edit" %}</a></div>
            <div><a href="{% url 'task_delete' task.id %}">{% trans "Delete" %}</a></div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}